#ifndef MUNINN_INT_H
#define MUNINN_INT_H


#define LOG_RB_SIZE         1024*1024            // DATA AVAILABLE IN LOGGER RINGBUFFEER
#define COMP_QUEUE_SIZE     8                    // MAXIMUM QUEUE SIZE (ELEMENTS IN THE Q)
#define COMP_MESSAGE_SIZE   256                  // MAXIMUM MESSAGE LENGTH (EACH ELEMENT IS LONG AT MOST)
#define P_SIZE              COMP_MESSAGE_SIZE    // MAXIMUM LOG PATH SIZE

#define F_MAX_SIZE          1024*1024            // MAXIMUM FILE SIZE BEFORE COMPRESSION


#endif